name: 'ğŸ Bug'
description: 'ë²„ê·¸ê°€ ìƒê²¼ì–´ìš”'
title: 'ğŸ [BUG] - <title>'
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        [Description] ë²„ê·¸ì— ê´€í•œ ì„¤ëª…ì„ ì ì–´ì£¼ì„¸ìš”.
      placeholder: |
        ì˜ˆ) ë™ì•„ë¦¬ ë…¸ì…˜ì„ ì¶”ê°€í•˜ì§€ ì•Šì•˜ëŠ”ë° 'ë…¸ì…˜ ë³´ëŸ¬ê°€ê¸°' ë²„íŠ¼ì´ ë– ìš”.
  - type: textarea
    id: additional
    attributes:
      label: Additional
      description: |
        [ì¶”ê°€ì‚¬í•­] ë³„ë„ë¡œ ì•Œë ¤ì¤˜ì•¼ í•  ì‚¬í•­ì´ë‚˜ ì¶”ê°€ì ìœ¼ë¡œ ê³µìœ í•  ë‚´ìš©ì´ ìˆë‹¤ë©´ ì‘ì„±í•´ì£¼ì„¸ìš”.
